spring:
  application:
    name: TestTask1

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:${POSTGRESQL_SERVER_PORT}/${POSTGRESQL_DATABASE}
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
    user:
      table: ${USER_TABLE_NAME}
    sensor:
      table: ${SENSOR_TABLE_NAME}
    measurement:
      table: ${MEASUREMENT_TABLE_NAME}
    role:
      table: ${ROLE_TABLE_NAME}


  jpa:
    database: postgresql
    show-sql: true

  data:
    jdbc:
      dialect: postgresql

  liquibase:
    change-log: db/changelog/main/main-changelog.yml

jwt:
  secret: ${JWT_SECRET}
  lifetime: ${JWT_LIFETIME}

server:
  port: ${SERVER_PORT}
