spring:
  application:
    name: TestTask1

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres1:${POSTGRESQL_SERVER_PORT}/${POSTGRESQL_DATABASE}
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
    user:
      table: ${USER_TABLE_NAME}
    sensor:
      table: ${SENSOR_TABLE_NAME}
    measurements:
      table: ${MEASUREMENTS_TABLE_NAME}


  jpa:
    database: postgresql
    show-sql: true

  data:
    jdbc:
      dialect: postgresql

  liquibase:
    change-log: db/changelog/main/main-changelog.yml

jwt:
  secret: ${JWT_SECRET}
  lifetime: ${JWT_LIFETIME}

server:
  port: 8080
